version: "3"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${PASSROOT}
      - TZ=${TZ}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    volumes:
      - ./db/config:/config
    ports:
      - ${PORTMYSQL}:3306
    restart: unless-stopped

  traccar:
    image: ${TRACCAR_IMAGE}
    container_name: traccar
#   depends_on:
#     - mariadb
    restart: unless-stopped
    volumes:
      - ./traccar/config/traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - ./traccar/log:/opt/traccar/logs:rw
    ports:
      - "5000-5150:5000-5150"
      - "8082:8082"
