version: "3"
services:
    dbgps:
        image: mysql:8.0.20
        container_name: dbgps
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file: .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./db:/var/lib/mysql
            - ./db/config:/etc/mysql/conf.d
            - ./db/backup:/opt/mysql/backup
        ports:
            - "3306:3306"

    traccar:
        image: ${TRACCAR_IMAGE}
        container_name: traccar
        depends_on:
            - dbgps
        restart: always
        volumes:
            - ./traccar/conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
            - ./traccar/log:/opt/traccar/logs:rw
        ports:
            - "5000-5150:5000-5150"
            - "8082:8082"